services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: erp-app
    container_name: erp-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: erp-simple
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8
    container_name: erp-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: erp-simple
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:stable
    container_name: erp-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  dbdata:
